<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add_1</name>
   <tag></tag>
   <elementGuidId>cc743160-48c2-420b-ba32-5a3b9f6d748c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@ng-click = 'addTool(tool)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vp-toolssearch__itembtn bg--cs07 text--center text--cs06 text--regular text--md absolute</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>addTool(tool)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show_tools&quot;)/div[@class=&quot;vp-addToolmodal absolute ng-scope&quot;]/div[@class=&quot;vp-addtoolmodal vp-control bg--white relative ng-scope&quot;]/div[@class=&quot;vp-addtoolmodal__body&quot;]/section[@class=&quot;vp-addtoolmodal__title&quot;]/div[@class=&quot;vp-addtoolmodal__findmachinewrap vertical--top mt--md ml--md left&quot;]/div[@class=&quot;vp-mmanagetab__findmachine max--height ng-scope&quot;]/div[@class=&quot;vp-toolssearch bg--white max--width ng-scope&quot;]/div[@class=&quot;vp-toolssearch__listwrapper max--width&quot;]/ul[@class=&quot;vp-toolssearch__list max--width ng-scope&quot;]/li[@class=&quot;vp-toolssearch__item vp-toolssearch__item&quot;]/div[@class=&quot;vp-toolssearch__iteminner vp-toolssearch__item--test pl--xxxl text--regular text--md clearfix&quot;]/div[@class=&quot;vp-toolssearch__itembtnwrap pointer relative right hidden&quot;]/span[@class=&quot;vp-toolssearch__itembtn bg--cs07 text--center text--cs06 text--regular text--md absolute&quot;]</value>
   </webElementProperties>
</WebElementEntity>
