<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_vp-userform__distributio</name>
   <tag></tag>
   <elementGuidId>4a78ce0d-8e48-4ca1-92eb-c7e5b30db7e0</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vp-userform__nameinput input--clear ng-untouched ng-invalid ng-not-empty ng-dirty ng-invalid-email ng-valid-required</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vp-userform__distributionlistinput</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>newUserGroupData.distribution_list</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[1]/div[@class=&quot;vp-app__deploytoolspage deployments-page max--height ng-scope&quot;]/div[@class=&quot;vp-manageusers max ng-scope&quot;]/div[@class=&quot;vp-manageusers__content max--height&quot;]/div[@class=&quot;vp-manageusers__tabs left max--width ng-scope&quot;]/div[@class=&quot;vp-tabs vp-tabs--default vp-tabs--usermanage vp-control relative max--width max--height clearfix ng-scope&quot;]/div[@class=&quot;vp-tabs__body overflow--auto left max--width&quot;]/div[@class=&quot;vp-tabs__addnewusertabcontent ng-scope&quot;]/div[@class=&quot;vp-addnewusercont vp-control max ng-scope&quot;]/div[@class=&quot;vp-addnewusercont__form ng-scope&quot;]/div[@class=&quot;vp-userform vp-userformnewuser vp-control max ng-scope&quot;]/form[@class=&quot;vp-userform__userform max ng-invalid ng-dirty ng-valid-parse ng-invalid-email ng-valid-required&quot;]/ul[@class=&quot;vp-userform__fieldslist text--cs03 pr--lg&quot;]/li[@class=&quot;vp-userform__fielditem vp-userform__nameitem pt--xxl&quot;]/tooltip[@class=&quot;tooltips _right _steady _multiline _ready active&quot;]/tip-cont[1]/tooltip[@id=&quot;tooltip_&quot;]/div[@class=&quot;vp-userform__fielditeminner&quot;]/div[@class=&quot;vp-userform__fieldcontent vp-userform__namecontent inblock&quot;]/input[@class=&quot;vp-userform__nameinput input--clear ng-untouched ng-invalid ng-not-empty ng-dirty ng-invalid-email ng-valid-required&quot;]</value>
   </webElementProperties>
</WebElementEntity>
