<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_tag1xz1or6</name>
   <tag></tag>
   <elementGuidId>9112b443-1a5d-4729-95f1-31b10191a7b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[@class=&quot;ng-scope&quot;]/body[1]/div[@class=&quot;vp-app__deploytoolspage max--height ng-scope&quot;]/div[@class=&quot;vp-edittools vp-control max--width ng-scope&quot;]/form[@class=&quot;ng-pristine ng-valid&quot;]/div[@class=&quot;vp-edittools__content bg--white max--height relative ng-scope&quot;]/div[@class=&quot;vp-edittools__contentbounded pr--xxxl&quot;]/div[@class=&quot;vp-edittools__toolinfo ng-scope&quot;]/div[@class=&quot;vp-toolinfo vp-toolinfo--new vp-control bg--white max--width ng-scope&quot;]/ul[@class=&quot;vp-userform__fieldslist text--cs03 pr--lg&quot;]/div[@class=&quot;vp-toolinfo__body max--width&quot;]/li[@class=&quot;vp-userform__fielditem vp-userform__emailitem pt--xxl&quot;]/div[@class=&quot;vp-userform__fielditeminner&quot;]/div[@class=&quot;vp-userform__fieldcontent vp-userform__emailcontent inblock&quot;]/div[@class=&quot;vp-versionform__content inblock&quot;]/div[@class=&quot;vp-versionform__prerequisitescontent--filled&quot;]/ul[@class=&quot;vp-versionform__prerequisiteslist clearfix&quot;]/li[@class=&quot;vp-versionform__prerequisitesitem mb--sm right ng-scope&quot;]/div[@class=&quot;vp-versionform__prerequisitesiteminner&quot;]/span[@class=&quot;ng-binding&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>tag1xz1or6</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[1]/div[@class=&quot;vp-app__deploytoolspage max--height ng-scope&quot;]/div[@class=&quot;vp-edittools vp-control max--width ng-scope&quot;]/form[@class=&quot;ng-pristine ng-valid&quot;]/div[@class=&quot;vp-edittools__content bg--white max--height relative ng-scope&quot;]/div[@class=&quot;vp-edittools__contentbounded pr--xxxl&quot;]/div[@class=&quot;vp-edittools__toolinfo ng-scope&quot;]/div[@class=&quot;vp-toolinfo vp-toolinfo--new vp-control bg--white max--width ng-scope&quot;]/ul[@class=&quot;vp-userform__fieldslist text--cs03 pr--lg&quot;]/div[@class=&quot;vp-toolinfo__body max--width&quot;]/li[@class=&quot;vp-userform__fielditem vp-userform__emailitem pt--xxl&quot;]/div[@class=&quot;vp-userform__fielditeminner&quot;]/div[@class=&quot;vp-userform__fieldcontent vp-userform__emailcontent inblock&quot;]/div[@class=&quot;vp-versionform__content inblock&quot;]/div[@class=&quot;vp-versionform__prerequisitescontent--filled&quot;]/ul[@class=&quot;vp-versionform__prerequisiteslist clearfix&quot;]/li[@class=&quot;vp-versionform__prerequisitesitem mb--sm right ng-scope&quot;]/div[@class=&quot;vp-versionform__prerequisitesiteminner&quot;]/span[@class=&quot;ng-binding&quot;]</value>
   </webElementProperties>
</WebElementEntity>
