<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_vp-versionform__editdep</name>
   <tag></tag>
   <elementGuidId>a008973a-b046-47cf-870a-6225013374ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[@class=&quot;ng-scope&quot;]/body[1]/div[@class=&quot;vp-app__deploytoolspage deployments-page max--height ng-scope&quot;]/div[@class=&quot;vp-distribution vp-deploytools max--height max--width ng-scope&quot;]/div[@class=&quot;vp-distribution__content max--height&quot;]/div[@class=&quot;vp-distribution__tabs left max--width ng-scope&quot;]/div[@class=&quot;vp-tabs vp-tabs--default vp-tabs--service vp-control relative max--width max--height clearfix ng-scope&quot;]/div[@class=&quot;vp-tabs__body overflow--hidden left max--width&quot;]/div[@class=&quot;vp-tabs__servicetabcontent ng-scope&quot;]/div[@class=&quot;vp-distributioncont relative ng-scope&quot;]/div[@class=&quot;vp-distributioncont__distributionsearch vertical--top inblock ng-scope&quot;]/div[@class=&quot;vp-permissionsselect bg--white max ng-scope&quot;]/section[@class=&quot;vp-permissionsselect__body max--width&quot;]/form[@class=&quot;ng-pristine ng-valid&quot;]/ul[@class=&quot;vp-permissionsselect__list&quot;]/li[@class=&quot;vp-permissionsselect__item vp-permissionsselect__itemdeploytools pt--xl max--width ng-scope&quot;]/div[@class=&quot;vp-permissionsselect__iteminner&quot;]/div[@class=&quot;noselect text--center inblock&quot;]/div[@class=&quot;vp-permissionsselect__admincol inblock&quot;]/div[@class=&quot;vp-teamsform__editcol vertical--top pt--md inblock&quot;]/button[@class=&quot;vp-versionform__editdeploydetails vp-uielement__button vp-uielement__button--edit&quot;][count(. | //button[@type = 'button']) = count(//button[@type = 'button'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vp-versionform__editdeploydetails vp-uielement__button vp-uielement__button--edit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>selectTag(tag._id.oid)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[1]/div[@class=&quot;vp-app__deploytoolspage deployments-page max--height ng-scope&quot;]/div[@class=&quot;vp-distribution vp-deploytools max--height max--width ng-scope&quot;]/div[@class=&quot;vp-distribution__content max--height&quot;]/div[@class=&quot;vp-distribution__tabs left max--width ng-scope&quot;]/div[@class=&quot;vp-tabs vp-tabs--default vp-tabs--service vp-control relative max--width max--height clearfix ng-scope&quot;]/div[@class=&quot;vp-tabs__body overflow--hidden left max--width&quot;]/div[@class=&quot;vp-tabs__servicetabcontent ng-scope&quot;]/div[@class=&quot;vp-distributioncont relative ng-scope&quot;]/div[@class=&quot;vp-distributioncont__distributionsearch vertical--top inblock ng-scope&quot;]/div[@class=&quot;vp-permissionsselect bg--white max ng-scope&quot;]/section[@class=&quot;vp-permissionsselect__body max--width&quot;]/form[@class=&quot;ng-pristine ng-valid&quot;]/ul[@class=&quot;vp-permissionsselect__list&quot;]/li[@class=&quot;vp-permissionsselect__item vp-permissionsselect__itemdeploytools pt--xl max--width ng-scope&quot;]/div[@class=&quot;vp-permissionsselect__iteminner&quot;]/div[@class=&quot;noselect text--center inblock&quot;]/div[@class=&quot;vp-permissionsselect__admincol inblock&quot;]/div[@class=&quot;vp-teamsform__editcol vertical--top pt--md inblock&quot;]/button[@class=&quot;vp-versionform__editdeploydetails vp-uielement__button vp-uielement__button--edit&quot;]</value>
   </webElementProperties>
</WebElementEntity>
