<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add</name>
   <tag></tag>
   <elementGuidId>1d6c8340-76e5-4d7d-8253-d3db647c0960</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ml--lg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+Add</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[1]/div[@class=&quot;vp-app__deploytoolspage deployments-page max--height ng-scope&quot;]/div[@class=&quot;vp-machines max ng-scope&quot;]/div[@class=&quot;vp-machines__component bg--white max--height relative&quot;]/div[@class=&quot;vp-machine__contentbounded max--height&quot;]/div[@class=&quot;vp-machines__tabs left max--width ng-scope&quot;]/div[@class=&quot;vp-tabs vp-tabs--default vp-tabs--machines vp-control relative max--width max--height clearfix ng-scope&quot;]/div[@class=&quot;vp-tabs__body overflow--auto left max--width&quot;]/div[@class=&quot;vp-tabs__mmanagecontent max ng-scope&quot;]/div[@class=&quot;vp-mmanagetab vp-control max inblock nowrap ng-scope&quot;]/section[@class=&quot;vp-mmanagetab__content vertical--top inblock&quot;]/div[@class=&quot;vp-mmanagetab__machinesectionwrap mt--xxl ml--md inblock ng-scope&quot;]/div[@class=&quot;vp-mmanagetab__verticaltabs mt--xl max--height ng-scope&quot;]/div[@class=&quot;vp-tabsvertical vp-control max--width max--height clearfix ng-scope&quot;]/div[@class=&quot;vp-tabsvertical__body bg--white left max--height relative&quot;]/div[@class=&quot;vp-tabsvertical__bodycontent max ng-scope&quot;]/div[@class=&quot;vp-machdetails vp-control pt--xxxl pr--xl pb--xxxl pl--xxxl bg--white clearfix max ng-scope&quot;]/form[@class=&quot;ng-pristine ng-valid ng-valid-required&quot;]/ul[@class=&quot;vp-machdetails__fieldslist text--cs03&quot;]/li[@class=&quot;vp-userform__fielditem vp-userform__roleitem pt--lg&quot;]/div[@class=&quot;vp-versionform vp-component bg--white max--width&quot;]/div[@class=&quot;vp-userform__fielditeminner&quot;]/environment-variables[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;vp-versionform__content inblock&quot;]/section[@class=&quot;vp-versionform__deploymentdetails&quot;]/div[@class=&quot;vp-versionform__deployitemlistwrap--filled&quot;]/div[1]/button[@class=&quot;vp-versionform__adddeploymentdetail vp-uielement__button vp-uielement__button--cleanenabled text--left&quot;]/span[@class=&quot;ml--lg&quot;]</value>
   </webElementProperties>
</WebElementEntity>
