<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select</name>
   <tag></tag>
   <elementGuidId>ac403146-602f-486f-85ff-3c9482d201a5</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vp-search__itembtn bg--cs07 text--center text--cs06 text--regular text--md absolute</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>selectMachineGroup(group._id.$oid)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[1]/div[@class=&quot;vp-app__deploytoolspage deployments-page max--height ng-scope&quot;]/div[@class=&quot;vp-machines max ng-scope&quot;]/div[@class=&quot;vp-machines__component bg--white max--height relative&quot;]/div[@class=&quot;vp-machine__contentbounded max--height&quot;]/div[@class=&quot;vp-machines__tabs left max--width ng-scope&quot;]/div[@class=&quot;vp-tabs vp-tabs--default vp-tabs--machines vp-control relative max--width max--height clearfix ng-scope&quot;]/div[@class=&quot;vp-tabs__body overflow--auto left max--width&quot;]/div[@class=&quot;vp-tabs__createmachinesbulk max ng-scope&quot;]/div[@class=&quot;vp-mmanagetab vp-control max inblock nowrap ng-scope&quot;]/section[@class=&quot;vp-mmanagetab__content vertical--top inblock&quot;]/div[@class=&quot;vp-mmanagetab__findmachinewrap vertical--top mt--md ml--md left&quot;]/div[@class=&quot;vp-mmanagetab__findmachine max--height ng-scope&quot;]/div[@class=&quot;vp-machinessearch vp-search bg--white max--width ng-scope&quot;]/div[@class=&quot;vp-search__listwrapper max--width&quot;]/ul[@class=&quot;vp-search__list max--width&quot;]/li[@class=&quot;vp-search__item ng-scope&quot;]/div[@class=&quot;vp-search__iteminner vp-search__item--test pl--xxxl text--regular text--md relative clearfix&quot;]/div[@class=&quot;vp-search__itembtnwrap pointer relative right relative hidden&quot;]/span[@class=&quot;vp-search__itembtn bg--cs07 text--center text--cs06 text--regular text--md absolute&quot;]</value>
   </webElementProperties>
</WebElementEntity>
