//REQUIRE CONFIG

require.config({
    baseUrl: "",
    waitSeconds: 0,
    paths: {
        // General Libraries and modules

        // angular
        'angular': 'static/node_modules/angular/angular.min',
        'angularTimer': 'static/node_modules/angular-timer/dist/angular-timer.min',
        'ngResource': 'static/node_modules/angular-resource/angular-resource.min',
        'uiRouter': 'static/node_modules/angular-ui-router/release/angular-ui-router.min',
        'ngCookies': 'static/node_modules/angular-cookies/angular-cookies.min',
        'toolTips' : 'static/node_modules/angular-tooltips/dist/angular-tooltips.min',
        'dropDownMultiSelect': 'static/node_modules/angularjs-dropdown-multiselect/dist/angularjs-dropdown-multiselect.min',
        'angular-smart-table':'static/components/audits/angular-smart-table/dist/smart-table.min',
        'ngFocus':'static/node_modules/ng-focus-if/focusIf.min',

        'moment': 'static/node_modules/moment/min/moment-with-locales',
        'humanizeDuration': 'static/node_modules/humanize-duration/humanize-duration',
        'jquery': 'static/node_modules/jquery/dist/jquery.min',
        // User defined Routes Modules
        'authenticationRoutesApp': 'static/components/authentication/authentication-route',
        'applicationRoutesApp': 'static/components/app/application-route',
        'deploymentRoutesApp': 'static/components/deployments/deployments-route',
        'machineRoutesApp': 'static/components/machines/machine-route',
        'cloneRoutesApp': 'static/components/clonerequests/clonerequests-route',
        'settingsRoutesApp' : 'static/components/settings/settings-route',
        'userRoutesApp' : 'static/components/manage-users/users-route',
        'deploymentUnitsRoutesApp' : 'static/components/deployment-unit/deploymentunit-route',
        'tagsRoutesApp' : 'static/components/manage-tags/tags-route',
        'pluginRoutesApp':'static/components/plugin/plugin-route',
        'monitoringRoutesApp':'static/components/monitoring/monitoring-route',
        'prerequisitesRoutesApp':'static/components/manage-prerequisites/prerequisites-route',
        'statesRoutesApp':'static/components/states/states-route',
        'flaxAttributeRoutesApp':'static/components/manage-fas/flexattribute-route',
        'deploymentPluginRoutesApp': 'static/components/deployment-plugins/deploymentplugins-route',
        'repositoryRoutesApp':'static/components/repository/repository-route',
         // User defined Controller Modules
        'appControllersApp': 'static/components/app/app-ctrl',
        'systemDataControllerApp': 'static/components/app/about-dpm/system-data-controller',
        'accountLogoControllerApp': 'static/components/authentication/login/account-logo-controller',
        'deployToolControllerApp': 'static/partials/tools/deploy-tools/deploy-tool-controller',
        'deployementRequestStepsControllerApp': 'static/components/deployments/deployment-details-content/deployement-request-steps-controller',
        'deployDUControllerApp': 'static/partials/deploy-du/deploy-du-controller',
        'manageMachineControllerApp': 'static/partials/machines/machine-controller',
        'addNewMachineControllerApp': 'static/components/machines/create-anew-machine-content/add-machine-controller',
        'editMachineControllerApp': 'static/components/machines/manage-machines-content/edit-machine-controller',
        'bulkMachineUploadControllerApp': 'static/components/machines/create-machines-bulk-content/bulk-machine-upload-controller',
        'addNewMachineGroupControllerApp': 'static/components/machines/create-anew-machine-group-content/create-machine-group-controller',
        'editMachineGroupControllerApp': 'static/components/machines/manage-machine-groups-content/edit-machine-group-controller',
        'manageMachineGroupsControllerApp': 'static/components/machines/manage-machine-groups-content/manage-machine-groups-controller',
        'deleteMachineGroupControllerApp': 'static/components/machines/manage-machine-groups-content/delete-machine-group-controller',
        'machineTabsComponent' : 'static/components/machines/tabs/tabs.component',
        'createAccountControllerApp': 'static/partials/clonerequests/create-clone-request/create-account-controller',
        'cloneRequestGridControllerApp': 'static/partials/clonerequests/clone-request-grid-controller',
        'cloneRequestStepsControllerApp': 'static/components/clonerequests/clone-requests-details-content/clone-request-steps-controller',
        'settingsViewControllerApp': 'static/partials/settings/settings-view-controller',
        'importExportControllerApp': 'static/partials/import-export/import-export-controller',
        'saveExportControllerApp':'static/components/import-export/save-export-file-content/save-export-controller',
        'deleteConfigurationControllerApp':'static/components/settings/delete-configuration-controller',
        'manageSynchronizationServiceControllerApp': 'static/partials/synchronization-services/manage-synchronization-service-controller',
        'synchronizationServiceControllerApp':'static/components/synchronization-services/create-new-sync-content/synchronization-service-controller',
        'editSynchronizationServiceControllerApp': 'static/components/synchronization-services/manage-synchronization-service-content/edit-synchronization-service-controller',
        'distributionServiceControllerApp': 'static/partials/distribution/distribution-service-controller',
        'deleteDistributionServiceControllerApp': 'static/partials/distribution/delete-distribution-service-controller',
        'resendDistributionServiceControllerApp': 'static/partials/distribution/resend-distribution-service-controller',
        'importToolControllerApp': 'static/partials/tools/show-new-tool/import-tool-controller',
        'updateToolControllerApp': 'static/partials/tools/show-updated-tool/update-tool-controller',
        'personalizeControllerApp': 'static/components/settings/personalize-content/personalize-controller',
        'editUserControllerApp' : 'static/partials/manage-users/edit-user-controller',
        'manageUsersControllerApp' : 'static/partials/manage-users/manage-users-controller',
        'addUsersControllerApp' : 'static/partials/manage-users/add-user-controller',
        'addBulkUsersControllerApp' : 'static/partials/manage-users/add-bulk-user-controller',
        'createUserGroupControllerApp' : 'static/partials/manage-users/add-usergroup-controller',
        'editUserGroupControllerApp' : 'static/partials/manage-users/edit-usergroup-controller',
        'deleteUserGroupControllerApp' : 'static/partials/manage-users/delete-user-group-controller',
        'manageUserGroupControllerApp' : 'static/partials/manage-users/manage-user-group-controller',
        'deleteRoleControllerApp' : 'static/partials/manage-users/delete-role-controller',
        'userListControllerApp' : 'static/partials/manage-users/user-list-controller',
        'deleteUserControllerApp' : 'static/partials/manage-users/delete-user-controller',
        'manageRolesControllerApp' : 'static/partials/manage-users/manage-roles-controller',
        'editRoleControllerApp' : 'static/partials/manage-users/edit-role-controller',
        'machineDetailsTabsComponent' : 'static/components/machines/tabs/verticaltabs/verticaltabs.component',
        // Machine Groups vertical tabs
        'machineGroupsDetailsTabsControllerApp' : 'static/components/machines/tabs/verticaltabs/machinegrouptabs.component',
        'manageSyncServicesComponent' : 'static/components/synchronization-services/tabs/tabs.component',
        'syncDetailsTabsComponent' : 'static/components/synchronization-services/tabs/verticaltabs/verticaltabs.component',
        'deploymentUnitDashboardControllerApp' : 'static/components/deployment-unit/dashboardDU/deployment-unit-dashboard-controller',
        'dashboardDUAllControllerApp' : 'static/components/deployment-unit/dashboardDU/tilegrid/dashboard-du-all-controller',
        'addNewDUControllerApp' : 'static/components/deployment-unit/create-du/create-new-du-controller',
        'editDUControllerApp' : 'static/components/deployment-unit/edit-du/edit-du-controller',
        'viewDUControllerApp' : 'static/components/deployment-unit/show-du/view-du-controller',
        'addNewDUSetControllerApp' : 'static/components/deployment-unit/create-du-sets/create-new-du-set-controller',
        'allDUSetControllerApp' : 'static/components/deployment-unit/dashboardDU/all-du-set-controller',
        'editDUSetControllerApp' : 'static/components/deployment-unit/edit-du-set/edit-du-set-controller',
        'viewDUSetControllerApp' : 'static/components/deployment-unit/show-du-set/view-du-set-controller',
        'editTagControllerApp' : 'static/components/manage-tags/manage-tag/manage-tag-component-controller',
        'manageTagsControllerApp' : 'static/components/manage-tags/tags-main-component-controller',
        'createNewTagControllerApp' : 'static/components/manage-tags/add-new-tag/add-new-tag-component-controller',
        'pluginControllersApp':'static/partials/plugin/plugin-controller',
        'runningServicesControllerApp':'static/partials/monitoring/running-services-controller',
        'viewReportsControllerApp':'static/partials/reports/view-reports-controller',
        'managePrerequisitesControllerApp': 'static/partials/manage-prerequisites/manage-prerequisites-controller',
        'addNewPrerequisiteControllerApp':'static/partials/manage-prerequisites/create-new-prerequisite-controller',
        'editPrerequisiteController':'static/partials/manage-prerequisites/edit-prerequisite-controller',
        'manageStatesControllerApp': 'static/partials/states/manage-states-controller',
        'addNewDUStateControllerApp': 'static/components/states/create-du-state-content/create-new-du-state-controller',
        'addNewDUSetStateControllerApp': 'static/components/states/create-duset-state-content/create-new-du-set-state-controller',
        'editDUSetStateControllerApp' : 'static/components/states/manage-duset-state-content/edit-du-set-state-controller',
        'stateTabsComponent' : 'static/components/states/tabs/tabs.component',
        'manageFlexAttributesControllerApp': 'static/components/manage-fas/flexible-attributes-main-controller',
        'editFlexAttributesControllerApp': 'static/components/manage-fas/manage-fas-content/flexible-attributes-edit-controller',
        'addNewFlexAttributesControllerApp': 'static/components/manage-fas/add-new-fa/flexible-attributes-new-controller',
        
        // User defined Services Modules
        'appServices': 'static/components/app/app-services',
        'authenticationServicesApp': 'static/components/authentication/authentication-services',
        'toolServicesApp': 'static/components/tools/tool-services',
        'toolSetServicesApp' : 'static/partials/tools/tool-set-services',
        'deploymentServicesApp': 'static/components/deployments/deployments-services',
        'machineServicesApp': 'static/components/machines/machine-services',
        'cloneServicesApp': 'static/components/clonerequests/clonerequests-services',
        'settingsServicesApp' : 'static/components/settings/settings-services',
        'userServicesApp' : 'static/partials/manage-users/users-services',
        'deploymentUnitsServicesApp' : 'static/components/deployment-unit/deploymentunit-services',
        'tagsServicesApp' : 'static/components/manage-tags/tags-services',
        'pluginServicesApp':'static/components/plugin/plugin-services',
        'monitoringServicesApp':'static/components/monitoring/monitoring-services',
        'prerequisitesServicesApp':'static/components/manage-prerequisites/prerequisites-services',
        'statesServicesApp':'static/components/states/states-services',
        'flexAttributeServicesApp':'static/components/directives/flexible-attributes/flexible-attributes-service',
        'deploymentPluginServicesApp': 'static/components/deployment-plugins/deploymentplugins-services',
        'proposedToolServicesApp' : 'static/partials/tools/proposed-tool-services',
        // Partials controller JS
        'loginControllerApp': 'static/components/authentication/login/login',
        'changePasswordControllerApp': 'static/components/authentication/change-password/change-password',
        'forgotPasswordControllerApp': 'static/components/authentication/forgot-password/forgot-password',
        'resetPasswordControllerApp': 'static/components/authentication/reset-password/reset-password',
        'createToolsControllerApp': 'static/partials/tools/create-tools//create-tools.partial',
        // Dashboard Partial
        'dashboardControllerApp': 'static/partials/dashboard/dashboard.partial',
        // Dashboard Components
        'navsideComponentControllerApp': 'static/components/dashboard/navaside/navaside.component',
        'toolDashboardHeaderComponentControllerApp': 'static/components/dashboard/header/header.component',
        'headerMessageComponentControllerApp': 'static/components/dashboard/header-message/headermessage.component',
        'toolDashboardFilterComponentControllerApp': 'static/components/dashboard/filter/filter.component',
        'allToolsComponentControllerApp': 'static/components/dashboard/tilegrid/all-tools/all-tools.component',
        'newToolsComponentControllerApp': 'static/components/dashboard/tilegrid/new-tools/new-tools.component',
        'updatedToolsComponentControllerApp' : 'static/components/dashboard/tilegrid/tool-updates/tool-updates.component',
        'toolSetListComponentControllerApp': 'static/components/dashboard/tilegrid/tool-sets/tool-sets.component',
        'recentRequestsComponentControllerApp': 'static/components/dashboard/tabs/recentrequests-body/recent-requests-body.component',
        'savedRequestsComponentControllerApp': 'static/components/dashboard/treeview/saved-requests/saved-requests-tree.component',
        'requestDetailsComponentControllerApp': 'static/components/dashboard/request-details-modal/requestdetailsmodal',
        'requestTabComponent' : "static/components/dashboard/tabs/tabs.component",
        'proposedToolsComponentControllerApp': 'static/components/dashboard/tilegrid/proposed-tools/proposed-tools.component',
        // Show tool Partial
        'showToolPartialControllerApp': 'static/partials/tools/show-tool/show-tool.partial',
        // show tool Components
        'showToolHeaderComponentControllerApp': 'static/components/tools/show-tool/header/header.component',
        'toolInfoComponentControllerApp': 'static/components/tools/show-tool/tool-info/toolinfo.component',
        'verticalTabComponentControllerApp': 'static/components/tools/show-tool/tabs/verticaltabs.component',
        'versionComponentControllerApp': 'static/components/tools/show-tool/version-form/versionsform.component',
        'screenshotBrowserComponentControllerApp': 'static/components/tools/show-tool/screenshots-browser/screenshots-browser.component',
        // Manage Deployment Plugins Partial
        'manageDeploymentPluginsControllerApp': 'static/components/deployment-plugins/manage-deployment-plugins.partial',
        // Manage Deployment Plugins Components
        'manageDeploymentPluginsTabComponentApp': 'static/components/deployment-plugins/tabs/tabs.component',
        'manageDeploymentPluginContentComponentApp': 'static/components/deployment-plugins/manage-deployment-plugins-content/managedeploymentplugincontent.component',
        'pluginListSearchComponentApp': 'static/components/deployment-plugins/plugin-list-search/pluginlistsearch.component',
        'uploadDeploymentPluginContentComponentApp': 'static/components/deployment-plugins/upload-deployment-plugin-content/uploaddeploymentplugincontent.component',
        'uploadDeploymentPluginFormComponentApp': 'static/components/deployment-plugins/upload-deployment-plugin-form/uploaddeploymentpluginform.component',
        // Create tool partials
        'createToolsPartialControllerApp' : 'static/partials/tools/create-tools//create-tools.partial',
        //Create tool components
        'createToolInfoComponentControllerApp' : 'static/components/tools/create-tools/tool-info/toolinfo.component',
        'createToolBarComponentControllerApp' : 'static/components/tools/create-tools/toolbar/toolbar.component',
        'createToolVerticalTabComponentControllerApp' : 'static/components/tools/create-tools/tabs/verticaltabs.component',
        'createToolVersionComponentControllerApp' : 'static/components/tools/create-tools/version-form/versionform.component',
        // Edit tool partials
        'editToolsPartialControllerApp' : 'static/partials/tools/edit-tools/edit-tools.partial',
        //Edit tool components
        'editToolInfoComponentControllerApp' : 'static/components/tools/edit-tools/tool-info/toolinfo.component',
        'editToolBarComponentControllerApp' : 'static/components/tools/edit-tools/toolbar/toolbar.component',
        'editToolVerticalTabComponentControllerApp' : 'static/components/tools/edit-tools/tabs/verticaltabs.component',
        'editToolVersionComponentControllerApp' : 'static/components/tools/edit-tools/version-form/versionform.component',
        // Show new tool Partial
        'showNewToolPartialControllerApp': 'static/partials/tools/show-new-tool/show-new-tool.partial',
        // show new tool Components
        'showNewToolHeaderComponentControllerApp': 'static/components/tools/show-new-tool/header/header.component',
        'showNewToolInfoComponentControllerApp': 'static/components/tools/show-new-tool/tool-info/toolinfo.component',
        'showNewToolVerticalTabComponentControllerApp': 'static/components/tools/show-new-tool/tabs/verticaltabs.component',
        'showNewToolVersionComponentControllerApp': 'static/components/tools/show-new-tool/version-form/versionsform.component',
        'showNewToolScreenshotBrowserComponentControllerApp': 'static/components/tools/show-new-tool/screenshots-browser/screenshots-browser.component',
        // Show Updated tool Partial
        'showUpdatedToolPartialControllerApp': 'static/partials/tools/show-updated-tool/show-updated-tool.partial',
        // show Updated tool Components
        'showUpdatedToolHeaderComponentControllerApp': 'static/components/tools/show-updated-tool/header/header.component',
        'showUpdatedToolInfoComponentControllerApp': 'static/components/tools/show-updated-tool/tool-info/toolinfo.component',
        'showUpdatedToolVerticalTabComponentControllerApp': 'static/components/tools/show-updated-tool/tabs/verticaltabs.component',
        'showUpdatedToolVersionComponentControllerApp': 'static/components/tools/show-updated-tool/version-form/versionsform.component',
        'showUpdatedToolScreenshotBrowserComponentControllerApp': 'static/components/tools/show-updated-tool/screenshots-browser/screenshots-browser.component',
        // Propose tool partials
        'proposeToolsPartialControllerApp' : 'static/partials/tools/propose-tools/propose-tools.partial',
        //Create tool components
        'proposeToolHeaderComponentControllerApp' : 'static/components/tools/propose-tools/header/header.component',
        'proposeToolInfoComponentControllerApp' : 'static/components/tools/propose-tools/tool-info/toolinfo.component',
        'proposeToolVerticalTabComponentControllerApp': 'static/components/tools/propose-tools/tabs/verticaltabs.component',
        'proposeToolVersionComponentControllerApp': 'static/components/tools/propose-tools/version-form/versionsform.component',
        'proposeToolBarComponentControllerApp' : 'static/components/tools/propose-tools/toolbar/toolbar.component',
        // Show Proposed tool Partial
        'showProposedToolPartialControllerApp': 'static/partials/tools/show-proposed-tool/show-proposed-tool.partial',
        // Show Proposed tool Components
        'showProposedToolHeaderComponentControllerApp': 'static/components/tools/show-proposed-tool/header/header.component',
        'showProposedToolInfoComponentControllerApp': 'static/components/tools/show-proposed-tool/tool-info/toolinfo.component',
        // Deployment partials
        'deploymentPartialControllerApp': 'static/partials/deployments/deployments.partial',
        // Deployment Components
        'deploymentRequestGridControllerApp': 'static/components/deployments/deployments-content/deploymentscontent.component',
        'deploymentVerticalTabsControllerApp': 'static/components/deployments/tabs/verticaltabs/verticaltabs.component',
        'deploymentDetailsContentControllerApp': 'static/components/deployments/deployment-details-content/deploymentdetailscontent.component',
        'DeploymentRequestsFilterControllerApp' : 'static/components/deployments/popups/openfilter.component',
        'revertDeploymentGroupControllerApp' : 'static/components/deployments/revert-deployment-group/revertdeploymentgroup',
        // Create tool set partials
        'createToolSetPartialControllerApp' : 'static/partials/tools/create-tool-sets/create-tool-set.partial',
        //Create tool components
        'createToolSetAddToolComponentControllerApp' : 'static/components/tools/create-tool-set/popups/addtool-popup.component',
        'createToolSetInfoComponentControllerApp' : 'static/components/tools/create-tool-set/tool-set-info/toolsetinfo.component',
        'createToolSetBarComponentControllerApp' : 'static/components/tools/create-tool-set/toolbar/toolbar.component',
        'createToolSetToolSearchComponentControllerApp' : 'static/components/tools/create-tool-set/tools-search-column/toolssearchcolumn.component',
        // Edit tool set partials
        'editToolSetPartialControllerApp' : 'static/partials/tools/edit-tool-set/edit-tool-set.partial',
        //Edit tool components
        'editToolSetAddToolComponentControllerApp' : 'static/components/tools/edit-tool-set/popups/addtool-popup.component',
        'editToolSetInfoComponentControllerApp' : 'static/components/tools/edit-tool-set/tool-set-info/toolsetinfo.component',
        'editToolSetBarComponentControllerApp' : 'static/components/tools/edit-tool-set/toolbar/toolbar.component',
        'editToolSetToolSearchComponentControllerApp' : 'static/components/tools/edit-tool-set/tools-search-column/toolssearchcolumn.component',
        // Show tool set partial
        'showToolSetPartialControllerApp': 'static/partials/tools/show-tool-set/show-tool-set.partial',
        // Show tool set components
        'showToolSetHeaderComponentControllerApp': 'static/components/tools/show-tool-set/header/header.component',
        'showToolSetInfoComponentControllerApp': 'static/components/tools/show-tool-set/tool-set-info/toolsetinfo.component',
        // Synchronization Services Components
        'syncRequestReportsComponentApp' : 'static/components/synchronization-services/sync-request-reports/syncrequestreports.component',
        'viewSyncRequestComponentApp' : 'static/components/synchronization-services/view-sync-request-content/viewsyncrequestcontent.component',
        // user defined directive Modules
        'flexAttributeDirectiveApp':'static/components/directives/flexible-attributes/flexible-attributes-directive',
        'deploymentPluginDirectiveApp': 'static/components/directives/deployment-plugin-directive',
        'disableSectionDirective':'static/components/directives/disable-section-directive',
        'environmentVariablesDirectiveApp':'static/components/directives/environment-variables/environment-variables-directive',
        'attentionModelDirectiveApp':'static/components/directives/attention-models/attention-modals-directive',
        'changePasswordDirectiveApp':'static/components/directives/change-password/change-password-directive',
        'retainBuildDirectiveApp':'static/components/directives/retain-build/retain-build-directive',
        // Auditing
        'auditingRoutesApp':'static/components/audits/audits-route',
        'auditPartialControllerApp':'static/partials/audits/audits.partial',
        'auditInfoControllerApp': 'static/components/audits/audits-info/audits.component',
        'auditServicesApp': 'static/components/audits/audits-services',
        // Repository controller
        'repositoryPartialControllerApp':'static/partials/repository/repository.partial',
        'EditRepositoryControllerApp':'static/components/repository/manage-repository-content/managerepositorycontent.component',
        'repositoryServicesApp':'static/components/repository/repository-service',
        'AddNewRepositoryControllerApp':'static/components/repository/add-new-repository/addnewrepositoryform.component'
    },
    shim: {
        'ngResource': ['angular'],
        'uiRouter': ['angular'],
        'ngCookies': ['angular'],
        'toolTips' : ['angular'],
        'angularTimer' : ['angular' ,'moment' ,'humanizeDuration' ],
        'dropDownMultiSelect' : ['angular'],
        'angular-smart-table':['angular'],
        'ngFocus':['angular']
    }
});

require(['angular', 'static/src/scripts/app'], function (app) {
    angular.bootstrap(document, ['app']);
});