<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select</name>
   <tag></tag>
   <elementGuidId>8d22268f-3637-403a-ab3a-1403e9376b9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[@class=&quot;ng-scope&quot;]/body[1]/div[@class=&quot;vp-app__toolspage max--height ng-scope&quot;]/div[@class=&quot;vp-edittools vp-control max--width ng-scope&quot;]/form[@class=&quot;ng-dirty ng-valid-parse ng-valid ng-valid-required&quot;]/div[@class=&quot;vp-edittools__content bg--white max--height relative&quot;]/div[@class=&quot;vp-edittools__contentbounded pr--xxxl&quot;]/div[@class=&quot;vp-edittools__toolinfo  ng-scope&quot;]/div[@class=&quot;vp-userform vp-userformnewuser vp-control max ng-scope&quot;]/ul[@class=&quot;vp-userform__fieldslist text--cs03 pr--lg&quot;]/li[@class=&quot;vp-userform__fielditem vp-userform__roleitem pt--lg&quot;]/div[@class=&quot;vp-versionform vp-component bg--white max--width&quot;]/div[@class=&quot;vp-userform__fielditeminner&quot;]/flexible-attributes[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;vp-versionform__content inblock&quot;]/section[@class=&quot;vp-versionform__deploymentdetails&quot;]/div[@class=&quot;vp-versionform__deployitemlistwrap--filled&quot;]/ul[1]/li[@class=&quot;vp-versionform__deploydetailsitem ng-scope&quot;]/div[@class=&quot;vp-versionform__deployiteminner bg--cs06 clearfix&quot;]/div[2]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;multiselect-parent btn-group dropdown-multiselect&quot;]/div[1][count(. | //div[@ng-transclude = 'toggleDropdown']) = count(//div[@ng-transclude = 'toggleDropdown'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-transclude</name>
      <type>Main</type>
      <value>toggleDropdown</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>toggleDropdown()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[1]/div[@class=&quot;vp-app__toolspage max--height ng-scope&quot;]/div[@class=&quot;vp-edittools vp-control max--width ng-scope&quot;]/form[@class=&quot;ng-dirty ng-valid-parse ng-valid ng-valid-required&quot;]/div[@class=&quot;vp-edittools__content bg--white max--height relative&quot;]/div[@class=&quot;vp-edittools__contentbounded pr--xxxl&quot;]/div[@class=&quot;vp-edittools__toolinfo  ng-scope&quot;]/div[@class=&quot;vp-userform vp-userformnewuser vp-control max ng-scope&quot;]/ul[@class=&quot;vp-userform__fieldslist text--cs03 pr--lg&quot;]/li[@class=&quot;vp-userform__fielditem vp-userform__roleitem pt--lg&quot;]/div[@class=&quot;vp-versionform vp-component bg--white max--width&quot;]/div[@class=&quot;vp-userform__fielditeminner&quot;]/flexible-attributes[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;vp-versionform__content inblock&quot;]/section[@class=&quot;vp-versionform__deploymentdetails&quot;]/div[@class=&quot;vp-versionform__deployitemlistwrap--filled&quot;]/ul[1]/li[@class=&quot;vp-versionform__deploydetailsitem ng-scope&quot;]/div[@class=&quot;vp-versionform__deployiteminner bg--cs06 clearfix&quot;]/div[2]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;multiselect-parent btn-group dropdown-multiselect&quot;]/div[1]</value>
   </webElementProperties>
</WebElementEntity>
