<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add</name>
   <tag></tag>
   <elementGuidId>49b6baae-ba1a-4e1e-90b3-0759906f636f</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ml--lg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+Add</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[1]/div[@class=&quot;vp-app__toolspage max--height ng-scope&quot;]/div[@class=&quot;vp-edittools vp-control max--width ng-scope&quot;]/form[@class=&quot;ng-dirty ng-valid-parse ng-valid ng-valid-required&quot;]/div[@class=&quot;vp-edittools__content bg--white max--height relative&quot;]/div[@class=&quot;vp-edittools__contentbounded pr--xxxl&quot;]/div[@class=&quot;vp-edittools__toolinfo  ng-scope&quot;]/div[@class=&quot;vp-userform vp-userformnewuser vp-control max ng-scope&quot;]/ul[@class=&quot;vp-userform__fieldslist text--cs03 pr--lg&quot;]/li[@class=&quot;vp-userform__fielditem vp-userform__roleitem pt--lg&quot;]/div[@class=&quot;vp-versionform vp-component bg--white max--width&quot;]/div[@class=&quot;vp-userform__fielditeminner&quot;]/div[@class=&quot;vp-versionform__content inblock&quot;]/section[@class=&quot;vp-versionform__deploymentdetails&quot;]/div[@class=&quot;vp-versionform__content inblock&quot;]/div[@class=&quot;vp-versionform__adddeployitem bg--cs06&quot;]/button[@class=&quot;vp-versionform__adddeploymentdetail vp-uielement__button vp-uielement__button--cleanenabled text--left&quot;]/span[@class=&quot;ml--lg&quot;]</value>
   </webElementProperties>
</WebElementEntity>
