<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_group_name</name>
   <tag></tag>
   <elementGuidId>1bdcfbda-bf51-4b7f-9188-d0180022e167</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vp-createnewmachform__aliasinput input--clear ng-untouched ng-not-empty ng-dirty ng-valid-parse ng-valid ng-valid-required</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>group_name</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>newMachineGroupData.group_name</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[1]/div[@class=&quot;vp-app__deploytoolspage deployments-page max--height ng-scope&quot;]/div[@class=&quot;vp-machines max ng-scope&quot;]/div[@class=&quot;vp-machines__component bg--white max--height relative&quot;]/div[@class=&quot;vp-machine__contentbounded max--height&quot;]/div[@class=&quot;vp-machines__tabs left max--width ng-scope&quot;]/div[@class=&quot;vp-tabs vp-tabs--default vp-tabs--machines vp-control relative max--width max--height clearfix ng-scope&quot;]/div[@class=&quot;vp-tabs__body overflow--auto left max--width&quot;]/div[@class=&quot;vp-tabs__createmachinesbulk max ng-scope&quot;]/div[@class=&quot;vp-createanewmach max ng-scope&quot;]/div[@class=&quot;vp-createanewmach__newmachineinfo pr--xl ng-scope&quot;]/div[@class=&quot;vp-createnewmachform vp-control bg--white max ng-scope&quot;]/form[@class=&quot;vp-createnewmachform__createanewmachine max--width ng-invalid ng-invalid-required ng-dirty ng-valid-parse&quot;]/ul[@class=&quot;vp-createnewmachform__fieldslist text--cs03 max--width&quot;]/li[@class=&quot;vp-createnewmachform__fielditem vp-createnewmachform__aliasitem pt--lg&quot;]/div[@class=&quot;vp-createnewmachform__fielditeminner&quot;]/div[@class=&quot;vp-createnewmachform__fieldcontent vp-createnewmachform__aliascontent inblock&quot;]/input[@class=&quot;vp-createnewmachform__aliasinput input--clear ng-untouched ng-not-empty ng-dirty ng-valid-parse ng-valid ng-valid-required&quot;]</value>
   </webElementProperties>
</WebElementEntity>
