fetch all configurations
---
tags:
   - Config

parameters:
- name: token
  in: header
  description: API key
  required: false
  type: string
  format: string
- name: access-token
  in: header
  description: API key
  required: false
  type: string
  format: string 

  
responses:
    200:
      description: Get all sync config successfully
      examples:
        result: "success"
        message: null
    404:
      description: exception in fetching sync config 
      examples:
        result: "failed"
        message: "Throws an exception"