fetch a configuration,referring by Config Id
---
tags:
  - Config

parameters:
- name: token
  in: header
  description: API key
  required: false
  type: string
  format: string
- name: access-token
  in: header
  description: API key
  required: false
  type: string
  format: string     
- name: configid
  in: path
  type: string
  required: true
  description: Config Id

responses:
    200:
      description: Get a configuration by Config Id
      examples:
        result: "success"
        message: null
    404:
      description: exception in fetching configuration
      examples:
        result: "failed"
        message: "Throws an exception"